import { defineConfig } from "vitepress";

// AUTO-GENERATED by Code Atlas assembler. Do not edit by hand — regenerate
// via 'atlas run'. Sidebar is grouped by layer, ordered by dependency topo-sort.

export default defineConfig({
  title: "Code Atlas",
  description: "Bottom-up guide, auto-generated by Code Atlas.",
  cleanUrls: true,
  themeConfig: {
    sidebar: {
      "/guide/": [
    { text: "复合 (Composite)", collapsed: false, items: [
      { text: "序章 · 响应式全景", link: `/guide/01-overview` },
      { text: "第 1 章 · Signal：可变单元与订阅集", link: `/guide/02-signal` },
      { text: "第 2 章 · Effect：依赖收集的诀窍", link: `/guide/03-effect` },
      { text: "第 3 章 · Computed：记忆化派生状态", link: `/guide/04-computed` },
      { text: "第 4 章 · Scheduler：批处理合并多次更新", link: `/guide/05-scheduler` },
      { text: "终章 · 组装与接缝地图", link: `/guide/06-assembly` }
    ] }
  ],
    },
    nav: [
      { text: "Home", link: "/" },
    ],
    outline: { level: [2, 3], label: "本页内容" },
    docFooter: { prev: "上一章", next: "下一章" },
  },
});
