/**
 * Stage 6 · Assemble (design §4, §11, ADR-0006). Build a self-contained
 * VitePress site from outline.json + chapter drafts.
 *
 * Deterministic TypeScript (no agent): copies drafts to site/guide/{nn}-{slug}.md,
 * generates .vitepress/config.ts (sidebar grouped by layer, ordered by topo),
 * index.md, and package.json (pinned vitepress).
 *
 * Per ADR-0006: site/ must build with just `bun install && bun run docs:build`,
 * independent of the engine repo.
 */
import {
  artifactPaths,
  ensureDir,
  readJson,
  readText,
  rmrf,
  runDir,
  siteDir,
  writeText,
  pathExists,
} from "../lib/io.ts";
import {
  markStageDone,
  markStageFailed,
  markStageRunning,
  type Manifest,
} from "../lib/manifest.ts";
import type { OutlineChapter } from "../agents/architect.ts";

interface OutlineFile {
  repo: string;
  chapters: OutlineChapter[];
  topoOrder: string[];
}

const VITEPRESS_VERSION = "^1.5.0";

export async function stageAssemble(m: Manifest): Promise<void> {
  console.log(`[stage:assemble] assembling VitePress site`);
  const runRoot = runDir(m.key);
  const site = siteDir(m.key);
  try {
    const outline = await readJson<OutlineFile>(artifactPaths.outline(m.key));
    const { chapters, topoOrder, repo } = outline;
    const bySlug = new Map(chapters.map((c) => [c.slug, c]));

    // reset site dir
    await rmrf(site);
    await ensureDir(site);
    await ensureDir(`${site}/guide`);
    await ensureDir(`${site}/.vitepress`);

    // 1. copy each draft → site/guide/{nn}-{slug}.md (nn = topo index)
    let copied = 0;
    for (let i = 0; i < topoOrder.length; i++) {
      const slug = topoOrder[i]!;
      const chapter = bySlug.get(slug);
      if (!chapter) continue;
      const nn = String(i + 1).padStart(2, "0");
      const draftPath = artifactPaths.draft(m.key, slug);
      if (!(await pathExists(draftPath))) {
        console.warn(`[stage:assemble] missing draft for ${slug} — skipping`);
        continue;
      }
      const draft = await readText(draftPath);
      // prepend front matter title for VitePress
      const page = addFrontMatter(chapter.title, draft);
      await writeText(`${site}/guide/${nn}-${slug}.md`, page);
      copied++;
    }

    // 2. generate .vitepress/config.ts (sidebar grouped by layer, topo-ordered)
    await writeText(`${site}/.vitepress/config.ts`, generateConfig(outline));

    // 3. index.md (homepage)
    const firstSlug = topoOrder[0] ?? "";
    const firstNn = "01";
    await writeText(
      `${site}/index.md`,
      generateIndex(repo, chapters.length, firstNn, firstSlug),
    );

    // 4. package.json (pinned vitepress, dev/build scripts)
    await writeText(`${site}/package.json`, generatePackageJson());

    markStageRunning(m, "assemble", `copied ${copied} chapters; generated site scaffold`);
    markStageDone(m, "assemble");
    console.log(`[stage:assemble] done — ${copied} chapters → site/`);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    markStageFailed(m, "assemble", msg);
    console.error(`[stage:assemble] FAILED: ${msg}`);
    throw e;
  }
}

function addFrontMatter(title: string, body: string): string {
  // avoid double front-matter if the writer already included one
  if (body.startsWith("---")) return body;
  return `---\ntitle: ${jsonEscape(title)}\n---\n\n${body}`;
}

function jsonEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Sidebar (design §11):
 *   - group by layer (primitive → composite → system)
 *   - within group, keep topoOrder
 *   - file ref: /guide/{nn}-{slug}
 */
function generateConfig(outline: OutlineFile): string {
  const { chapters, topoOrder } = outline;
  const bySlug = new Map(chapters.map((c) => [c.slug, c]));
  const pos = new Map(topoOrder.map((s, i) => [s, i]));
  const layerOrder: OutlineChapter["layer"][] = ["primitive", "composite", "system"];
  const layerLabel: Record<string, string> = {
    primitive: "原子概念 (Primitive)",
    composite: "复合 (Composite)",
    system: "系统 (System)",
  };

  const sidebarGroups = layerOrder
    .map((layer) => {
      const items = chapters
        .filter((c) => c.layer === layer)
        .sort((a, b) => (pos.get(a.slug) ?? 0) - (pos.get(b.slug) ?? 0));
      if (items.length === 0) return null;
      const text = layerLabel[layer] ?? layer;
      const children = items
        .map((c) => {
          const nn = String((pos.get(c.slug) ?? 0) + 1).padStart(2, "0");
          return `      { text: ${JSON.stringify(c.title)}, link: \`/guide/${nn}-${c.slug}\` }`;
        })
        .join(",\n");
      return `    { text: ${JSON.stringify(text)}, collapsed: false, items: [\n${children}\n    ] }`;
    })
    .filter((x) => x !== null);

  const sidebar = `[\n${sidebarGroups.join(",\n")}\n  ]`;

  return `import { defineConfig } from "vitepress";

// AUTO-GENERATED by Code Atlas assembler. Do not edit by hand — regenerate
// via 'atlas run'. Sidebar is grouped by layer, ordered by dependency topo-sort.

export default defineConfig({
  title: ${JSON.stringify(outline.repo || "Code Atlas")},
  description: "Bottom-up guide, auto-generated by Code Atlas.",
  cleanUrls: true,
  themeConfig: {
    sidebar: {
      "/guide/": ${sidebar},
    },
    nav: [
      { text: "Home", link: "/" },
    ],
    outline: { level: [2, 3], label: "本页内容" },
    docFooter: { prev: "上一章", next: "下一章" },
  },
});
`;
}

function generateIndex(
  repo: string,
  chapterCount: number,
  firstNn: string,
  firstSlug: string,
): string {
  const startLink = firstSlug ? `/guide/${firstNn}-${firstSlug}` : "/";
  return `---
layout: home
hero:
  name: ${JSON.stringify(repo || "Code Atlas")}
  text: 自底向上的源码解读
  tagline: 由 Code Atlas 自动生成 · ${chapterCount} 章
  actions:
    - theme: brand
      text: 开始阅读
      link: ${startLink}
features:
  - title: 自底向上
    details: 章节按概念依赖排序，前置知识已在前文讲过。
  - title: 可复刻
    details: 每章配最小可运行的 ts/js 复刻代码。
---

::: tip
本站由 [Code Atlas](https://github.com/) 从源码自动生成。
:::
`;
}

function generatePackageJson(): string {
  return JSON.stringify(
    {
      name: "code-atlas-site",
      version: "0.0.0",
      private: true,
      type: "module",
      scripts: {
        docs: "vitepress dev",
        "docs:dev": "vitepress dev",
        "docs:build": "vitepress build",
        "docs:preview": "vitepress preview",
      },
      devDependencies: {
        vitepress: VITEPRESS_VERSION,
      },
    },
    null,
    2,
  );
}
